services:
  - type: web
    name: finflow-api
    runtime: node
    plan: free
    region: oregon
    autoDeploy: true
    rootDir: server
    buildCommand: npm install && npx prisma generate && npx prisma db push && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: file:./dev.db
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: "*"
      - key: UPLOAD_DIR
        value: ./uploads
