services:
  - type: web
    name: finflow-api
    runtime: node
    plan: free
    region: oregon
    rootDir: server
    buildCommand: npm install && node scripts/prepare-db.js --push && npm run build
    startCommand: node scripts/prepare-db.js && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_dKNBhjz4Me0m@ep-billowing-tree-b45dtxzq-pooler.c-6.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: JWT_SECRET
        value: finflow_production_jwt_secret_token_secure_permanent_key_2026
      - key: CORS_ORIGIN
        value: "*"
      - key: UPLOAD_DIR
        value: ./uploads
